[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2024"
authors = ["Colm Murphy <colmmurphy016@gmail.com>"]

[dependencies]
md5 = "0.8.0"
rayon = "1.11.0"

[profile.release]
codegen-units = 1
lto = "fat"
# rustflags = ["-C", "target-cpu=native"]
